### PR TITLE
Improve ruleset. Add proper check for the textdomain

### PR DESCRIPTION
**Pull request by burhandodhy**

### CODE REVIEW

**Comment by jeffpaul** [comment]
@burhandodhy are you able to resolve the merge conflict?

**Comment by burhandodhy** [comment]
@jeffpaul but there is no conflict message on my end. Should I send the new PR ?

**Comment by pattonwebz** [comment]
The conflict is probably due to the master branch now being different to the one you made the PR against. If you run a `git rebase master` it may resolve the conflicts. You should then be able to push the resolved branch here and this PR will update :)

**Comment by burhandodhy** [comment]
Actually I deleted the forked repo and its not easy to restore the deleted repo and push the changes :| . I sent the new PR https://github.com/WordPress/twentytwenty/pull/342 and I'm closing this PR.

**Pull request closed without merging**
