### PR TITLE
Padding difference in front end and back end for Table block in Gutenberg.

### PR DESCRIPTION
**Pull request by Swapnildhanrale**
The theme support for the Block Style's is not added.

```
// Add support for Block Styles.
add_theme_support( 'wp-block-styles' );
```

And `12px` padding added to the table block cell content as below:

```
.editor-styles-wrapper .wp-block-table .wp-block-table__cell-content {
      padding: 12px;
}
```

By default, the block editor added `0.5em` to the table cell content which is overridden by above CSS.

For that, the table does not look the same in block editor and on the front end.

Fixes: #697

### CODE REVIEW

**Comment by ianbelanger79** [comment]
Thanks for submitting your patch @Swapnildhanrale, however the theme contains it's own block styles, thus the core block styles are not enqueued. You can update your patch to remove the core block styles and we will test again. Thanks

**Comment by Swapnildhanrale** [comment]
Hello @andersnoren I have just removed the block style support you can please check and merge my PR

**Comment by ianbelanger79** [comment]
This does not fix the table issues at the moment. Padding is still off between back and front end. Also when using the `Fixed width table cells option` and Wide or Full width, the table is misaligned and is not wide or full width.

**Comment by ianbelanger79** [comment]
Closing because the PR is out-of-date and the issues have been fixed in another PR

**Pull request closed without merging**
