### PR TITLE
Fix/use h1 in home template

### LINKED ISSUE #23: H1 tag should be used on both home and front-page cases
H1 tag should ideally be used on both home and front-page cases.

### PR DESCRIPTION
**Pull request by audrasjb**
H1 tag should ideally be used on both home and front-page cases.

Fixes #23

### CODE REVIEW

**Comment by senadir** [comment]
I think https://github.com/WordPress/twentytwenty/pull/24/commits/37a854bee622a52ba71b972615c58cedd762a4ba belongs to https://github.com/WordPress/twentytwenty/pull/18

other than that, LGTM

**Comment by joyously** [comment]
The other two commits are extra.
This PR does not address the H1 in index.php.
https://github.com/WordPress/twentytwenty/blob/81b787b65c3e1a19c7e230cf4b49729ebd970760/index.php#L32

**Comment by audrasjb** [comment]
PR refreshed.

**Comment by audrasjb** [comment]
Thanks @senadir for your check.
@joyously Thanks too, by the way I guess this one should be addressed in an other PR.

**Comment by joyously** [comment]
Really, it belongs together. See my comment in the issue.

**Pull request merged**
