### PR TITLE
Add accent color to archive titles

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #234

If you guys think regex isn't a good idea, I can add the span tags manually to all the items via filter...

### CODE REVIEW

**Comment by carolinan** [comment]
Does this fit better in inc/template-tags.php ?

**Comment by acosmin** [comment]
@carolinan I think I screwed this one :) any Ideas what to do, should I redo the PR?

**Comment by carolinan** [comment]
yes if you need to, of course

**Comment by acosmin** [comment]
@carolinan I think it's ok now, only 1 file changed...

**Comment by carolinan** [comment]
Hm... actually what about the title for the search results page, what do you think? Add this for now?

**Comment by acosmin** [comment]
@carolinan What do you think of changing [this](https://github.com/WordPress/twentytwenty/blob/666b5a8d16d9edf22bc74be37a59c4a78d21f821/index.php#L30)

to:
```
$archive_title = sprintf( 
    '%1$s %2$s', 
    '<span class="color-accent">' . __( 'Search:', 'twentytwenty' ) . '</span>', 
    '&ldquo;' . get_search_query() . '&rdquo;' 
);
```

**Comment by carolinan** [comment]
Test ran it, I think it looks really good =)

**Comment by acosmin** [comment]
👍

**Pull request merged**
