### PR TITLE
touch devices: open submenus on the desktop horizontal menu

### LINKED ISSUE #790: Unable to access a submenu item of the Desktop Horizontal Menu on tablet (>1000px)
On a tablet (1024px for an iPad or 1366px for an iPad Pro for example) when the user clicks on the menu item (or on its icon) which has a submenu, it always loads the parent page. The submenu appears briefly but it's impossible to click on a submenu item.

The submenu works well inside the modal as the user can click on the icon to open the submenu.

### PR DESCRIPTION
**Pull request by carolinan**
Hopefully Fixes #790

### CODE REVIEW

**Comment by westonruter** [comment]
@carolinan This fix is not working for me. I'm getting a JS error:

image

**Comment by pattonwebz** [comment]
@westonruter I'm afraid that I missed this when I merged :(

I will try and look at this as soon as I can but if you have any ideas for a fix then let me know.

**Comment by westonruter** [comment]
@pattonwebz I'm opening a PR.

**Comment by pattonwebz** [comment]
Thank you for this :raised_hands: :heart: 

Also as an aside I know you have been working to make sure this theme is AMP compatible and if there are other JS changes required for that let me know as we still have a very small window for adjusting important aspects and being AMP ready is important in my view

**Comment by westonruter** [comment]
@pattonwebz See #971. 

Otherwise, the theme has been made fully AMP compatible via the AMP plugin thanks to great work by @schlessera: https://github.com/ampproject/amp-wp/issues/3342, https://github.com/ampproject/amp-wp/pull/3403, https://github.com/ampproject/amp-wp/pull/3606, https://github.com/ampproject/amp-wp/issues/3604, https://github.com/ampproject/amp-wp/issues/3616, https://github.com/ampproject/amp-wp/pull/3628, https://github.com/ampproject/amp-wp/pull/3621, https://github.com/ampproject/amp-wp/issues/3618, https://github.com/ampproject/amp-wp/issues/3617, https://github.com/ampproject/amp-wp/pull/3620, https://github.com/ampproject/amp-wp/pull/3594, https://github.com/ampproject/amp-wp/pull/3578, https://github.com/ampproject/amp-wp/pull/3574, https://github.com/ampproject/amp-wp/issues/3570, https://github.com/ampproject/amp-wp/issues/3569, https://github.com/ampproject/amp-wp/issues/3559

In lieu of the Twenty Twenty theme being AMP-compatible in and of itself, the AMP plugin shims the compatibility via via its core theme sanitizer. Perhaps in the future new core themes could be developed leveraging AMP components (especially when they can be installed locally as node packages via [Bento AMP](https://blog.amp.dev/2019/05/01/amp-as-your-web-framework/)). But in the meantime, it's not so bad to maintain AMP compatibility for the core themes externally since they don't really change over time.

**Pull request merged**
