### PR TITLE
Fix - Scroll to top removed when modal is opened

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #585

* scroll to top removed
* modal will remain on the same position
* For cover template I had to move `.screen-height` on the `div.cover-header` element + change a few styles. Otherwise the cover would jump top/down and its height is wrong.
* works with the admin bar.

### CODE REVIEW

**Comment by andersnoren** [comment]
Using `position: absolute` to position the `.cover-header-inner-wrapper` makes it possible for the contents of the cover header to overflow at the top, so that's a no go, unfortunately :)

image

If it's only the Cover Template that has issues when we remove the scroll to the top, is it possible to only scroll to the top on the Cover Template?

**Comment by acosmin** [comment]
@andersnoren it is possible. You want to try that out :)?

**Comment by andersnoren** [comment]
@acosmin Let's!

**Comment by acosmin** [comment]
@andersnoren done

**Comment by yannickiki** [comment]
@acosmin @andersnoren  There is a problem when the cover is taller than 100 vh, the overlay is too short.
cover

Adding this CSS fixes it.
```
.cover-header-inner-wrapper {
 position: relative;
}
```

@acosmin I've tested your code and I've removed the part that scroll to the top on cover template and I can't see any issues. How can I replicate your issues with the cover template?

**Comment by acosmin** [comment]
@andersnoren @yannickiki I think I got it to work with cover template 😄

**Comment by yannickiki** [comment]
@acosmin I don't understand the need of the following lines. 

https://github.com/WordPress/twentytwenty/blob/73944794795b56d5ba4983c3a4b876fa67716109/assets/js/index.js#L188-L192

https://github.com/WordPress/twentytwenty/blob/73944794795b56d5ba4983c3a4b876fa67716109/assets/js/index.js#L224-L228

I don't see the connection between the cover template banner overlay and the menu modal.

I've tested without the lines above, but with the addition of 
`.cover-header-inner-wrapper { position: relative;}`that fixes the [cover overlay height issues](https://github.com/WordPress/twentytwenty/pull/667#issuecomment-536515845). I don't see any bugs. Am I missing something ? 🙂

**Comment by acosmin** [comment]
Sometimes the simplest answer is the right one 😄  you were right @yannickiki 🎢

**Pull request merged**
