### PR TITLE
UPDATE #119: Center search form

### LINKED ISSUE #119: Search results. Align the search form in center
The search form in search results page, align in the left side. It will be more useful if this search fom align in the center of page. Τhe user's eye scans and reads in a logical order.

search-results

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #119 

<table>
<tr>
<td>Before:
<br><br>

</td>
<td>After:
<br><br>

</td>
</tr>
</table>

### CODE REVIEW

**Comment by andersnoren** [comment]
@nielslange Sorry, completely missed this one two days ago. The search form label is set to `width: 100%;` in #261, so the search form will fill out the entire width of its container on this page when both PRs are merged. Thumbs up from me on that.

I think you can remove the entire `twentytwenty_search_form` function though – the only thing it seems to add from the default markup is the `.section-inner` class, and we don't need that class on the label element.

**Comment by nielslange** [comment]
> @nielslange Sorry, completely missed this one two days ago. The search form label is set to `width: 100%;` in #261, so the search form will fill out the entire width of its container on this page when both PRs are merged. Thumbs up from me on that.

No worries, @andersnoren!

> I think you can remove the entire `twentytwenty_search_form` function though – the only thing it seems to add from the default markup is the `.section-inner` class, and we don't need that class on the label element.

Sure, I'll do that now.

**Comment by nielslange** [comment]
@andersnoren I just updated the PR and removed the custom form. Feel free to merge it. 😀

**Comment by andersnoren** [comment]
@nielslange Awesome! Travis seems to dislike the lack of a newline character at the end of `functions.php`. Can you take a look?

**Comment by nielslange** [comment]
Sure, @andersnoren. Give me a minute to fix it.

**Comment by nielslange** [comment]
@andersnoren The PHPCS had been fixed and Travis seems to be happy now. 😀

**Pull request merged**
