### PR TITLE
add @wordpress/scripts package

### PR DESCRIPTION
**Pull request by Ismail-elkorchi**
Related : https://github.com/WordPress/twentytwenty/issues/35

This PR adds `@wordpress/scripts` package, and adds the `lint:css` and `lint:js` scripts to `package.json`. It also adds Travis configuration to make use of the new scripts.

### CODE REVIEW

**Comment by ntwb** [comment]
Looking great @Ismail-elkorchi 

I've added a `.stylelintrc.json` file to exclude the `no-descending-specificity` rule (this is also done in Gutenberg)

I'll make a couple more tweaks later as required

**Comment by ntwb** [comment]
I've updated all the files that will be covered by the _lint_ additions in this PR.

We should merge those first I believe to help prevent Travis CI failing on all pull requests until the changes are made.

**Comment by ntwb** [comment]
There are two issues, #408 and #409 that require resolving for the stylelint lint to tests to pass, both these should be resolved before merging this PR.

**Comment by ntwb** [comment]
There is one issue, #410 that requires resolving for the ESLint lint to tests to pass, this should be resolved before merging this PR.

**Comment by ianbelanger79** [comment]
This PR is failing Travis because of the ES5 JS we are using. Is there a way to tell it to use ES5 standards? @Ismail-elkorchi

**Comment by Ismail-elkorchi** [comment]
@ianbelanger79  I've added a `.eslintrc`file to make use of the ES5 rulesets.

But, as I said in https://github.com/WordPress/twentytwenty/issues/410#issuecomment-533799823, I think that writing code in ES6 syntax and transform it using the build script in `@wordpress/scripts` is best approach to take.

**Comment by Ismail-elkorchi** [comment]
I've added a rule in the `.eslintrc` file to use only the browser environment. This will prevent Travis from complaining about undefined objets when it's irrelevant.

**Comment by Ismail-elkorchi** [comment]
@ianbelanger79 I'll make a PR to fix the remaining errors in the `index.js` file.

**Comment by ianbelanger79** [comment]
I think @acosmin is working on that, but if you can get it done first, go ahead, we are running out of time quickly

**Comment by acosmin** [comment]
I'm done, wait 2 minutes :)

**Pull request merged**
