### PR TITLE
Fixed mobile menu interaction with adminbar in mobile view

### PR DESCRIPTION
**Pull request by acosmin**
@ianbelanger79 this should be merged :) it solves an issue with the wpadminbar height in mobile view.

### CODE REVIEW

**Comment by ianbelanger79** [comment]
I just merged the Coding Standards for the index.js file and now there are conflicts. Could you refresh your PR?

**Comment by acosmin** [comment]
I'll do it once the linted version is merge :)

**Comment by acosmin** [comment]
@ianbelanger79 it seems that the linted versions will have to wait 😄 this can be merged.

**Comment by acosmin** [comment]
fixed the conflict

**Comment by acosmin** [comment]
Closing this, fixed in #437

**Pull request closed without merging**
