### PR TITLE
Fix - Unable to access a submenu item of the Desktop Horizontal Menu on tablet (>1000px)

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #790

### CODE REVIEW

**Comment by yannickiki** [comment]
@acosmin Your code works well for opening the submenu on tablet. However currently the user can't close the submenu by clicking outside it.

**Comment by acosmin** [comment]
@yannickiki please try it now.

**Comment by yannickiki** [comment]
@acosmin I've tried and there are some issues. It's difficult to tell exactly what's going on because sometimes it's possible to close the submenu by clicking outside it. But sometimes it's simply impossible to close it. Moreover the problems happen on a real tablet (iPad), when I emulate a device on chrome it works well. It's tricky🤔.

**Comment by acosmin** [comment]
I think I'm going to have to pass on this issue :) I don't own an iPad and can't really test it in a proper way. I'll let someone else handle it :( sorry

**Pull request closed without merging**
