### PR TITLE
Fix - When closing the modals, focus should be moved back to the "opener" element

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #81

### CODE REVIEW

**Comment by afercia** [comment]
I left a couple _post mortem_ comment on the commit https://github.com/WordPress/twentytwenty/commit/11dc91ff610065a47eb04d88b3091692ad428105

Sorry I was not able to review in time. Will see if I have some bandwidth for improvements in the next days.

**Comment by yannickiki** [comment]
@acosmin This PR makes a bug reappear (#585).

The clicked element should be focused before (and not after) the window scroll back to its position.

**Current:**
https://github.com/WordPress/twentytwenty/blob/b3559060fa980acf68da37d6ba3bbfb87077fefb/assets/js/index.js#L234-L241

**Fix:**

```
 if ( clickedEl !== false ) { 
 	clickedEl.focus(); 
 	clickedEl = false; 
 } 

_win.scrollTo( 0, Math.abs( _win.twentytwenty.scrolled + getAdminBarHeight() ) ); 
  
_win.twentytwenty.scrolled = 0; 
```

**Comment by acosmin** [comment]
@yannickiki Thanks, I'll check it out tomorrow and pus a PR if it's needed. Or you can do it if you want to 😄

**Comment by yannickiki** [comment]
@acosmin You're too fast! 😄

**Pull request merged**
