### PR TITLE
index.js - back to es5

### PR DESCRIPTION
**Pull request by acosmin**
- Removed dependencies
- Converted back to es5
- Removed `twentytwentyGetQueryStringValue()`, not used.

For #410 

@ntwb You should probably merge this before adding linting and we can fix any issues if it reports something.

### CODE REVIEW

**Comment by ianbelanger79** [comment]
@acosmin Travis is failing when I try to merge #363 and it is due to numerous errors in the index.js file, see travis results here https://travis-ci.com/WordPress/twentytwenty/jobs/237803811

**Comment by acosmin** [comment]
@ianbelanger79 I can fix those errors, just one thing, can I please add `/*eslint-env browser*/` https://eslint.org/docs/rules/no-undef#environments

This is for all the `window, NodeList is not defined`... they are defined 😄

**Comment by ianbelanger79** [comment]
Absolutely add `/*eslint-env browser*/` if needed.

**Comment by Ismail-elkorchi** [comment]
@ianbelanger79 @acosmin I'll make Eslint use the browser environment in https://github.com/WordPress/twentytwenty/pull/363. This will get rid of  errors about the undefined variables.

**Pull request merged**
