### PR TITLE
#354 - Fix tab navigation

### LINKED ISSUE #354: Closing the expanding menu with keyboard only requires tabbing backwards
When you reach the last menu item of the open, expanded menu (in this case a social link), the next item when you tab is on the page. It is difficult the see where the focus is, because the menu remains open. 

Expected: The next item should be the close button.

Currently, to reach the close button we need to tab backwards through all the menu items.

### PR DESCRIPTION
**Pull request by c4rl0sbr4v0**
Return to close button after tabbing to the last item of the menu.

This pull requests fixes #354 
Tested on Chrome and Safari on Mac:

Without social links on the menu:
menu_navigation_tabs_no_social

With social links on the menu:
menu_navigation_tabs

With two menus:
menu_navigation_tabs_no_social_two_menus

### CODE REVIEW

**Comment by carolinan** [comment]
Hi,
please try to fix the error from the Travis report.

The focus needs to be contained within the modal, it is still possible to tab backwards (shift + tab) 
and focus on items on the page hidden the menu.

When I tab away forward from the last menu item, the first menu item is focused, and not the close button.

**Comment by c4rl0sbr4v0** [comment]
Hi! I will work on that tomorrow morning.
I put the prevent default in order not to happen the last issue "When I tab away forward from the last menu item, the first menu item is focused, and not the close button." 
Can you please tell me with how that happened (Browser and system)

Thanks!

**Comment by carolinan** [comment]
I use Chrome Version 77.0.3865.90 on windows.
I don't know JS well enough to help you further.  This codepen was recommended, if it helps: 
https://dev.to/islam/how-to-trap-focus-inside-a-modal-2791

We have a commit freeze for beta 1 in a few hours :)

**Comment by c4rl0sbr4v0** [comment]
Let's fix it before then :-)

**Comment by carolinan** [comment]
This works for the expanded menu in Chrome, Firefox and Edge but not in IE11.

For the mobile menu, there is no close button, so we need to pick a focus target for when we tab forward from the last item.
This should probably be the menu toggle,  mobile-nav-toggle,
or, it could be the search if the search is enabled, or the site title, since both these items comes _before_ the menu toggle in the visual order.

**Comment by c4rl0sbr4v0** [comment]
Cool! I will try it in IE asap :-) Also I will update the mobile part :-)

**Comment by carolinan** [comment]
@acosmin Do you have time to look at this? :)

**Comment by acosmin** [comment]
@carolinan Let's wait for #557 to be merged and after that the conflicts should be fixed. Maybe @sgomes could also take a look at this.

**Comment by c4rl0sbr4v0** [comment]
I will test it today on IE, conflicts for my part are easy, I just add a function an execute it :-)

**Comment by c4rl0sbr4v0** [comment]
@carolinan Updated and tested on IE11, please let me know if is also working for you. 

> For the mobile menu, there is no close button, so we need to pick a focus target for when we tab forward from the last item.
> This should probably be the menu toggle, mobile-nav-toggle,
> or, it could be the search if the search is enabled, or the site title, since both these items comes _before_ the menu toggle in the visual order.

This will be fixed on Friday by 13:00 UTC+2 :-)

**Comment by c4rl0sbr4v0** [comment]
Everything working as requested!

**Comment by carolinan** [comment]
Mobile menu:
+ When I tab forward from the last menu item, it now targets the menu toggle.
- I can't tab backwards from the menu toggle. It does not matter if the menu is open or not.

**Comment by carolinan** [comment]
OK after testing and discussing we will merge this now and work from here to do some changes to the mobile menu, including adding the close button.

**Pull request merged**
