### PR TITLE
Implemented the Image Overlay Text Color option

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #235

Prefixes should be handled in another PR

Also, I changed the defaults to lowercase to match what the Customizer color picker saves.

### CODE REVIEW

**Comment by carolinan** [comment]
twentytwenty_get_customizer_css has moved to inc/custom-css.php

**Comment by acosmin** [comment]
I'm working on it right now :)

**Comment by acosmin** [comment]
@carolinan done, did you guys remove the post meta and excerpt from the cover overlay?

**Comment by carolinan** [comment]
Hmm no, that was not intentional, posts are meant to show both, pages are only meant to show the arrow.

**Comment by acosmin** [comment]
If you want I can redo them in this PR

**Comment by carolinan** [comment]
Ok, I trust that you see which code that needs to be moved from entry-header to content-cover :)

**Comment by acosmin** [comment]
@carolinan it should work now :)

**Comment by carolinan** [comment]
I can't find a mockup that shows the excerpt or meta, but looking back,
the original page-header.php only showed the arrow for pages, not for posts.
Posts showed excerpt and meta.

**Comment by carolinan** [comment]
entry-header.php is not used for the cover template, so ideally the code for the template should be removed from this file.

**Comment by acosmin** [comment]
I think the arrow was available for posts as well, from what I remember...

**Comment by andersnoren** [comment]
The arrow was only displayed for pages with the cover template, originally. It gets a bit messy with posts that have both a title, excerpt, meta items, and the arrow.

**Comment by acosmin** [comment]
Rearranged them... :)

**Pull request merged**
