### PR TITLE
UPDATE #461: Load index.js synchronously

### LINKED ISSUE #461: The modal and the search button doesn't work when not logged in
To reproduce :

1. Click on the search button and the menu button and make sure that they work.
2. Log out from WordPress, return to the front end; now the buttons should not work.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #461

### CODE REVIEW

**Comment by acosmin** [comment]
You should also probably set to `true` `wp_enqueue_script()`'s `$in_footer`

**Comment by nielslange** [comment]
@acosmin I thought that loading the `index.js` in the footer would cause this issue. That's why I haven't used `$in_footer = true` but kept `$in_footer = false`.

**Comment by Ismail-elkorchi** [comment]
@nielslange  The change made in https://github.com/WordPress/twentytwenty/pull/453/commits/aa391fe21a4bb987bf14cc0b50cd58576bfbc9d2 fixes https://github.com/WordPress/twentytwenty/issues/461.

**Comment by ianbelanger79** [comment]
Fixed in #453

**Pull request closed without merging**
