### PR TITLE
Dropdown category widget exceeds parent div

### PR DESCRIPTION
**Pull request by Adhitya03**
Drop-down category widget exceeds parent div on Twenty Twenty Theme.
[Before patch - exceeds parent div](https://prnt.sc/pb7uo7)
[After patch](https://prnt.sc/pb7v32)

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@Adhitya03 Patch looks good to me.

@andersnoren Can you please check it.

**Comment by Adhitya03** [comment]
All checks have passed, thank you @andersnoren..

**Comment by andersnoren** [comment]
@Adhitya03 Thank you! What's your WordPress.org username? I need to add you to the contributors.md file.

**Comment by Adhitya03** [comment]
my wp.org username is adhitya03, Thank you.

**Pull request merged**
