### PR TITLE
Fix - Remove old unused code for accent colors

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #551

### CODE REVIEW

**Comment by acosmin** [comment]
I think there's a problem with the Travis build on this one 😄

**Comment by nielslange** [comment]
@acosmin Let me quickly look up the issue.

**Comment by nielslange** [comment]
@acosmin Guess Travis had a hiccup. I ran the build again and it passed now. :)

**Comment by acosmin** [comment]
thanks

**Pull request merged**
