### PR TITLE
#722 Fix social icons

### PR DESCRIPTION
**Pull request by glauberm**
All the SVGs were a little off, so I rebuilt them. I also reordered the GitHub one, that was not following the alphabetical order.

### CODE REVIEW

**Comment by carolinan** [comment]
What _exactly_ does "Little off" and "rebuilt" mean?

**Comment by glauberm** [comment]
@carolinan They're fundamentally the same icons. I'll use the facebook one to demonstrate it. Here's the old icon with an added border to show its limits:

old-icon

It has an irregular whitespace in it (that's what I meant by "a little off"), which makes it scale irregularly. My first thought was to change its `width`, `height` and `viewport`, thinking that it would make the whitespace disappear. Unfortunately, it didn't:

failed-attempt

I've even tried to change the `x` an `y` attributes, believing that would do it, but it didn't. I'm not sure why. Anyway, I decided to follow my usual SVG workflow and open the file on Inkscape, make the canvas fit the drawing and then save it as an [optimized SVG](https://www.integraxor.com/optimize-inkscape-svg-files/) with a precision of 4 digits for the coordinates (that's what I meant by "rebuilt"). That resulted on basically the same icon, but with no whitespace at all:

new-icon

I realize that the optimal solution would be to don't change the `path` coordinates at all, but I was unable to solve the problem without doing that. Perhaps we could "rebuilt" them again with more precision... Let me now what you think.

**Comment by pattonwebz** [comment]
This looks like a nice little tweak could save people from doing micro adjustments via CSS in their projects if they use the icons from the theme. That being said I think any changes to icons like this will need to wait until after a release is made as we are currently running the RC, let's see if any feedback comes back about this needed that could make us consider the misalignment a bug.

**Comment by glauberm** [comment]
Fixed by #933

**Pull request closed without merging**
