### PR TITLE
ADD #43: Add screenshot

### LINKED ISSUE #43: Add screenshot
Show the beauty of this theme by adding a screenshot:

Screenshot 2019-09-07 at 09 42 54

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #43 

<table>
<tr>
<td>Before:
<br><br>
43 - before

</td>
<td>After:
<br><br>
43 - after

</td>
</tr>
</table>

@andersnoren Feel free to replace screenshot.png with a more suitable one if you like to. 😉

### CODE REVIEW

**Comment by andersnoren** [comment]
Looking good! Can you update the readme.txt file with the following as well?

```
== Licenses ==

Image in screenshot.png from PxHere
License: Creative Commons Zero (CC0), https://creativecommons.org/publicdomain/zero/1.0/
URL: https://pxhere.com/sv/photo/1333652
```

**Comment by dingo-d** [comment]
Hi! @nielslange, could you also pull the screenshot through the ImageOptim or tinypng to reduce its size? Currently, it's 966KB and that seems a bit excessive for a screenshot in my opinion (plus something that we at TRT are trying to teach authors to size down so that the theme bundle is not too big) 🙂

**Comment by carolinan** [comment]
If I see correctly this image is of the British Museum? They do not allow photography for commercial use.

https://www.britishmuseum.org/about_us/services/images_and_photography.aspx

**Comment by nielslange** [comment]
@carolinan Don't you think the photo is fine to use as it's from https://pxhere.com/en/photo/1333652 and marked with

> CC0 Public Domain
> 
> Free for personal and commercial use
> No attribution required

**Comment by nielslange** [comment]
The license had been added to the readme.txt, @andersnoren, and the image had been optimized using https://imageoptim.com/online had now 295 kB, @dingo-d. The updated PR can be found in #134.

**Comment by carolinan** [comment]
No not without proof that the photographer had permission.

**Comment by nielslange** [comment]
@andersnoren Based on https://github.com/WordPress/twentytwenty/pull/98#issuecomment-529320743 could you provide another screenshot?

**Comment by andersnoren** [comment]
@nielslange Yep! I'll take a look at finding a good replacement this evening.

**Comment by ntwb** [comment]
The image should be fine, it is for non-commercial use and the photographer made it CC0

**Comment by nielslange** [comment]
@ntwb As far as I understood @carolinan it's not clear if the photographer was authorized to make the image available via https://pxhere.com/en/photo/1333652 in the first place.

**Comment by carolinan** [comment]
@andersnoren Any luck finding new images?

**Comment by andersnoren** [comment]
Sorry, this one completely slipped my mind. I'll need to update the screenshot with the changes to the header as well, so I think I'll create an entirely new PR for it. Should get it submitted within the hour.

**Pull request closed without merging**
