### PR TITLE
Adds padding for paragraphs in full-width columns block

### PR DESCRIPTION
**Pull request by luminuu**
The media queries used here reflect the media queries for the columns block from core. The changes exclusively work for paragraphs which are direct child elements of a single `wp-block-column`, where the `wp-block-columns` wrapper is set as `alignfull`.

@media ( max-width: 599px ) : paragraphs get the same width as the section-inner class.

@media ( min-width: 600px ) : there's a maximum of two columns displayed, so all columns need to get either padding-left or padding-right via :nth-child(odd) or :nth-child(even).

@media ( min-width: 782px ) : all columns are displayed in one row, so only the first and last child items need some padding.

### CODE REVIEW

**Comment by nielslange** [comment]
@andersnoren Would you mind taking a look at change as proposed in https://github.com/WordPress/twentytwenty/pull/707#issue-323401431?

**Comment by luminuu** [comment]
I have updated the CSS to match the requirements in #459 in my latest commit: f1d5376 

I added support for the group block, added a `:not(.has-background-color)` pseudoclass to avoid double paddings and removed the first `>` to apply this to all nested elements.

**Comment by luminuu** [comment]
@andersnoren Thanks for the feedback! I updated the targeting of the group block as you suggested.

**Comment by ianbelanger79** [comment]
Hi @luminuu, what is your WordPress username? Please let me know asap, thanks

**Comment by luminuu** [comment]
Hey @ianbelanger79, it's the same as my Github username: https://profiles.wordpress.org/luminuu

**Comment by nielslange** [comment]
> Hey @ianbelanger79, it's the same as my Github username: https://profiles.wordpress.org/luminuu

@ianbelanger79 I've added @luminuu to https://github.com/WordPress/twentytwenty/blob/master/CONTRIBUTORS.md in https://github.com/WordPress/twentytwenty/pull/811 and added you as a reviewer. 😀

**Pull request merged**
