### PR TITLE
UPDATE #597: Decrease list indent on small screens

### LINKED ISSUE #597: Smaller screens list indent seem significant
The indent for lists seems a little too much on smaller screens:

image

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #597 / This PR affects devices with a screen width up to 479px. 

<table>
<tr>
<td>Before:
<br><br>

#597 - before

</td>
<td>After:
<br><br>

#597 - after

</td>
</tr>
</table>

### CODE REVIEW

**Comment by joyously** [comment]
Did you try the ordered list with a two digit number?
And why change it only for small windows?

**Comment by nielslange** [comment]
> Did you try the ordered list with a two digit number?

I've adjusted the indent both for `ol` and `ul`, thus, the two-digit numbers are affected by that change as well.

> And why change it only for small windows?

 I've only changed it for small windows as on big screens the indents are not affecting the usability/readability, whereas on small screens they did.

**Comment by joyously** [comment]
I didn't mean that the two digit number wasn't affected. I wondered if you tried it with a two digit number to see if it was too far left. The first digit is often cut off or overhangs the line where everything else is aligned.
Big screens look better aligned, just like small screens.

**Comment by nielslange** [comment]
@joyously The left-space is indeed a bit narrow. I'll create an additional issue to further adjust this one.

**Pull request merged**
