### PR TITLE
use `esc_html__` instead of `esc_html`

### PR DESCRIPTION
**Pull request by itowhid06**

### CODE REVIEW

**Comment by andersnoren** [comment]
@itowhid06 Merged, thanks! What's your WordPress.org username?

**Comment by itowhid06** [comment]
@andersnoren,my WordPress.org username is `itowhid06`. Thanks :)

**Comment by ocean90** [comment]
@andersnoren This needs to be reverted, see #176 for background.

**Comment by andersnoren** [comment]
@ocean90 I'll create a new issue and PR for changing it to `__()`. Before this PR, the string wasn't translatable.

**Pull request merged**
