### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by nielslange**
Added @GlennMartin1 (WordPress.org: [hometowntrailers](https://profiles.wordpress.org/hometowntrailers/)) as contributor.

### CODE REVIEW

**Comment by jeffpaul** [comment]
FYI, I'm still reviewing a couple things before confirming I don't see any additional folks to add to this listing.

**Comment by jeffpaul** [comment]
Relates to #399

**Comment by jeffpaul** [comment]
Note that I'm reviewing [merged PRs](https://github.com/WordPress/twentytwenty/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+) for related issues to catch any well-detailed issues, testing, or feedback for additional props.

**Comment by jeffpaul** [comment]
Ok, I've completed my review/analysis and have no further updates.  Note that I couldn't track down the WordPress.org usernames for @okpierre or @yannickiki so hopefully either (1) someone else knows it and can get it added to the 5.3 credits or (2) they chime with their .ORG username so it can be added to the 5.3 credits.  🤞

**Comment by okpierre** [comment]
@jeffpaul intimez thanks

**Pull request merged**
