### PR TITLE
Updates to RTL stylesheets

### PR DESCRIPTION
**Pull request by ianbelanger79**

### CODE REVIEW

**Comment by nielslange** [comment]
@ianbelanger79 How can we ensure that these chances don’t get overwritten when running `npm run build` in the future?

**Comment by ntwb** [comment]
> How can we ensure that these chances don’t get overwritten when running npm run build in the future?

If RTL files require certain things to not be overwritten then using the RTLCSS _control directives_ to ignore as required is the solution to that, see:
https://rtlcss.com/learn/usage-guide/control-directives/

**Comment by nielslange** [comment]
Thanks, @ntwb. I'll create another PR to ensure that @ianbelanger79's changes will not be overwritten in the future.

**Comment by nielslange** [comment]
@ianbelanger79 I might have misunderstood your PR. You haven't added custom styles to the RTL styles but you've synced them with the LTR sheets, correct?

**Comment by ianbelanger79** [comment]
That is correct @nielslange I just ran `npm run build:rtl` before packaging for Beta 3

**Pull request merged**
