### PR TITLE
`WordPress` shouldn't be translatable.

### PR DESCRIPTION
**Pull request by juanfra**
WordPress shouldn't be translatable.

**Fixes:** https://github.com/WordPress/twentytwenty/issues/178

**WP Username:** juanfra

### CODE REVIEW

**Comment by xlmnxp** [comment]
@juanfra why not?

**Comment by juanfra** [comment]
Because it is a trademark, and it haven't been translated in any other theme.

**Comment by xlmnxp** [comment]
@juanfra no
we write `trademark` in Arabic 
`WordPress` > `ووردبريس`

**Comment by juanfra** [comment]
Thanks for your response. It seems that's always like that in core themes at least. You can take a look:

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentynineteen/footer.php#L28

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentyseventeen/template-parts/footer/site-info.php#L21

https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentysixteen/footer.php#L63

**Comment by tobifjellner** [comment]
Even if we don't translate WordPress, some languages still need to transliterate it into other type of scripts.

**Comment by ianbelanger79** [comment]
WordPress does need to be translatable, so I am closing this PR. Thanks for your submission @juanfra

**Comment by juanfra** [comment]
@ianbelanger79 so you're saying that all of the other core themes are wrong?

**Comment by tobifjellner** [comment]
@juanfra There was a short discussion in Slack: https://wordpress.slack.com/archives/C02RP4VMP/p1568130355315700

**Comment by juanfra** [comment]
Thank you @tobifjellner! I see your interaction with `@poena` where she asks you and you confirm it shouldn't be translatable. I'm assuming then, that all of the other core themes are wrong.

**Comment by tobifjellner** [comment]
You can make core tickets for the previous bundled themes, where applicable. :)

**Comment by juanfra** [comment]
Cool, thanks!

**Comment by senadir** [comment]
we can also make the assumption that other theme didn't consider it

**Pull request closed without merging**
