### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by nielslange**
In comparison to https://github.com/WordPress/twentynineteen/ the license on https://github.com/WordPress/twentytwenty/ still doesn't show in the repo overview. Therefore, I copied the LICENSE from https://github.com/WordPress/twentynineteen/blob/master/LICENSE to https://github.com/WordPress/twentytwenty/blob/master/LICENSE.

### CODE REVIEW

**Comment by carolinan** [comment]
Why was all the WordPress specific information removed?

**Comment by ntwb** [comment]
image

It shows up for me and as @carolinan pointed out the WordPress specific information should not be removed from the `LICENSE`

**Comment by nielslange** [comment]
> Why was all the WordPress specific information removed?

@carolinan I copied the license 1:1 from the Twenty Nineteen theme, which shows the license type in the repo overview. My assumption was that by using the identical file that the license type would also show for the Twenty Twenty repo.

**Twenty Nineteen:**



**Twenty Twenty:**



While Twenty Twenty shows `View license`, Twenty Nineteen shows ` GPL-2.0`.

cc: @ntwb

**Comment by ntwb** [comment]
Gutenberg is the same with just "View License", this is because GitHub can detect what license is in use, but as WordPress uses an amended GPL license GitHub doesn't detect that, but we should *not* remove the specific WordPress amendments/additions of the license, if anything the Twenty Nineteen license should probably be updated

**Comment by nielslange** [comment]
Thanks for your explanation, @ntwb, and consider this issue as done! 😀

**Pull request closed without merging**
