### PR TITLE
UPDATE #362: Adjust z-index of cover header

### LINKED ISSUE #362: z-index issue with the search modal and template-cover
1. Open a page that has template-cover selected
2. Open the search modal
3. The post meta (title, excerpt) can be selected without closing the modal.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #362

### CODE REVIEW

**Comment by andersnoren** [comment]
Hm, setting it to 100 will cause the site header to be placed on top of the menu modal on desktop though. 

Setting the z-index to 100 on mobile and updating it to 2 on → 1000 px should do it.

**Comment by nielslange** [comment]
Thanks for checking this, @andersnoren. I'll adjust the CSS code accordingly.

**Comment by nielslange** [comment]
@andersnoren and @acosmin: With https://github.com/WordPress/twentytwenty/pull/364/commits/16a511075609a32ab442728613bca642b24ebce9 I adjusted this PR based on your feedback in https://github.com/WordPress/twentytwenty/pull/364#issuecomment-533133231 an https://github.com/WordPress/twentytwenty/issues/362#issuecomment-533129277. Feel free to give it another test.

**Comment by carolinan** [comment]
Some CSS linting errors right now, but it works well for me (tested in Chrome, Firefox, Edge and IE11 on different widths.)

**Comment by carolinan** [comment]
..Did I create these linting issues when I tried to solve the conflict? >.<

**Pull request merged**
