### PR TITLE
Fix color issues on the Cover Template

### LINKED ISSUE #716: Color issues on the Cover Template
Currently the value of the "Header & Footer Background Color" is applied on the header text `.overlay-header .header-inner` (site title, tagline, menu) and submenus `.primary-menu ul` of the cover template:
https://github.com/WordPress/twentytwenty/blob/fd7477fbafffe69473cff99855884c11eda5e3be/functions.php#L653-L654

which means that if you set a dark color for the "Header & Footer Background Color", the header text and submenu text are dark thus unreadable on a cover.

menu

Moreover if you try to change the "Image Overlay Text Color" value to white, you can't because white is the default value.

### PR DESCRIPTION
**Pull request by andersnoren**
Fixes #716 by adding a `body:not(.overlay-header)` check to the `.primary-menu ul` targeting in `twentytwenty_get_elements_array()`, matching existing targeting for the cover template.

### CODE REVIEW

**Comment by dianeco** [comment]
@andersnoren It only fixes the submenu, the header text (menu, site title) is still unreadable. 
In `twentytwenty_get_elements_array()`, is there a reason to apply the value of "Header & Footer Background Color" to the overlay header text ` .overlay-header .header-inner`?

https://github.com/WordPress/twentytwenty/blob/45db061150abb34a36a4fbb1f5d281367bb4bbae/functions.php#L653-L654

IMO, the overlay header color should be white unless the user specifies a color for "Image Overlay Text Color".
Currently, if I set black for "Header & Footer Background Color", and keep the white default value for "Image Overlay Text Color", the header text is black instead of white.

color

**Comment by ianbelanger79** [comment]
@dianeco What is your WP username? Please let me know asap, thanks.

**Comment by dianeco** [comment]
@ianbelanger79 My WP username is [@dianeco](https://profiles.wordpress.org/dianeco/)

**Comment by nielslange** [comment]
> @ianbelanger79 My WP username is @dianeco

@ianbelanger79: Apparently, @dianeco had been added to https://github.com/WordPress/twentytwenty/blob/master/CONTRIBUTORS.md already. All good thus. 😀

**Pull request merged**
