### PR TITLE
Add separators to archive pages, update pagination

### LINKED ISSUE #99: Add styles to the newer / older post pagination
The newer / older post pagination is missing styles and does not yet match the initial screenshots.
Pagination.php should also be moved to the parts folder.

A decision needs to be made regarding https://github.com/WordPress/twentytwenty/issues/93 ,
_Icon-only controls_

In the mobile screenshot, only the arrow icons show and the text "Older /  Newer posts" is hidden.

If we choose to show both the icon and text, there is not enough room on small screens
to show the text, arrows and page numbers in one line.

Instead, the navigation could be split into 3 lines:

mobile-archive-pagination

And two lines if only one of the texts are displayed:

mobile-archive-pagination2

### PR DESCRIPTION
**Pull request by andersnoren**
Includes separators between posts on archive pages using `<hr />` elements, to simplify shared styles between the entry content separators. I've set the separators to `aria-hidden="true"` – please let me know if that should be changed to something else.

I've also added a matching separator to the pagination, and tested a solution for the problem with the items not being centered when there's no "Older Posts" or "Newer Posts" links being output. The solution either prepends of appends a placeholder element matching the missing one, and sets it to `aria-hidden="true"` and `visiblity: hidden` (not sure if both are needed). It's not a very neat solution, but it gives us consistent spacing between the items in the pagination regardless of which page we're on.

Fixes #99.

### CODE REVIEW

**Comment by carolinan** [comment]
When I test this in IE11, there is a large horizontal scroll when the width is over 1000px.

**Comment by andersnoren** [comment]
There's an issue in the site header in IE11. I'm going to try and find a fix for it tomorrow morning.

**Comment by carolinan** [comment]
Was the nav for https://github.com/WordPress/twentytwenty/issues/73 removed in an earlier PR? I don't see it as part of this.

**Comment by ianbelanger79** [comment]
Will fix #323

**Comment by andersnoren** [comment]
> There's an issue in the site header in IE11. I'm going to try and find a fix for it tomorrow morning.

Added a fix for this in #359.

**Comment by carolinan** [comment]
Merged with a reservation for #73 being fixes as soon as possible.

**Pull request merged**
