### PR TITLE
Move starter_content to primary menu to avoid vanishing on mobile

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Update #828 to address the starter_content vanishing on mobile with the default menu setup. This will remove the expanded desktop menu and place all items in the primary menu. With the current starter_content setup most items are added to the 'Desktop Expanded Menu' which vanishes on mobile.

### CODE REVIEW

**Comment by ianbelanger79** [comment]
Closing this PR as it is failing travis and we cannot change the starter content at this point.

**Comment by garrett-eclipse** [comment]
Thanks @ianbelanger79 shall I refresh for 5.3.1?
It's unfortunate we'll be unable to address this critical issue before the theme is released. As it stands any user adopting the existing starter content will have the majority of their content inaccessible on mobile.

**Comment by pattonwebz** [comment]
Reopening this so it can be worked on some more for future release. It's been flagged a few times that the current menu setup is confusing for people so we should do something about this soon (and maybe we can squeeze this one in as a need for UX reasons but if not it can go after release_

**Comment by garrett-eclipse** [comment]
I replaced this corrupt branch with #955

**Pull request closed without merging**
