### PR TITLE
Update Ensure link to read more is preserved in Continue reading button 

### PR DESCRIPTION
**Pull request by carolinan**
credits gravityrail, byalextran

### CODE REVIEW

**Comment by carolinan** [comment]
Underline works well on RTL, and the link works.
[

](url)

**Comment by joyously** [comment]
> Tested with custom colors, RTL, custom read more text.

Is it the Read More or is it the Continue Reading? Be sure the right thing was tested.

**Comment by carolinan** [comment]
I have tested the read more block.

**Comment by andersnoren** [comment]
Same.

**Comment by carolinan** [comment]
I can't get the other continue reading link to show actually. It only shows me ` […]`

**Comment by joyously** [comment]
It seems to me that the code that was changed is the filter for the parameter passed to `the_content()`, which is *not* the Read More tag (or block), and is a strange way for the theme to do it since there is no option for the user to change the text. The theme would simply pass a different argument to `the_content()` instead of using a filter, unless it is intent on using the core default argument.

**Pull request merged**
