### PR TITLE
UPDATE #773: Fix RTL alignments

### LINKED ISSUE #773: RTL: text aligned blocks are reversed, some aligned blocks reversed
The block styles loaded on the front end contain the correct rules for `.has-text-align-left` and `.has-text-align-right`, but the theme styles override with the wrong direction. These should just be removed.

The core blocks aligned left, right, center in LTR:
![left-right-center-LTR](https://user-images.githubusercontent.com/7957680/66261714-141cfc80-e798-11e9-86bc-7a819e933e20.jpg)

Here is the same post in RTL:
![left-right-center-RTL](https://user-images.githubusercontent.com/7957680/66261717-18e1b080-e798-11e9-9d36-61415d5545a4.jpg)

The problem with the Media/Text blocks is due to CSS in the block styles. I opened an issue for it on [GB repo](https://github.com/WordPress/gutenberg/issues/17787). Here is how it looks on RTL with one CSS rule disabled:
![media-text-with-smaller-media-RTL](https://user-images.githubusercontent.com/7957680/66261743-7bd34780-e798-11e9-9dfb-ee9bac0e834d.jpg)

-----------------------------
Here is the test content:
```
<!-- wp:heading {"align":"left","level":4} -->
<h4 class="has-text-align-left">h4 left</h4>
<!-- /wp:heading -->

<!-- wp:heading {"align":"right","level":4} -->
<h4 class="has-text-align-right">h4 right</h4>
<!-- /wp:heading -->

<!-- wp:heading {"align":"center","level":4} -->
<h4 class="has-text-align-center">h4 center</h4>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left"} -->
<p class="has-text-align-left">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec mollis. Quisque convallis libero in sapien pharetra tincidunt. Aliquam elit ante, malesuada id, tempor eu, gravida id, odio. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"right"} -->
<p class="has-text-align-right">Maecenas suscipit, risus et eleifend imperdiet, nisi orci ullamcorper massa, et adipiscing orci velit quis magna. Praesent sit amet ligula id orci venenatis auctor. Phasellus porttitor, metus non tincidunt dapibus, orci pede pretium neque, sit amet adipiscing ipsum lectus et libero. Aenean bibendum.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center"> Curabitur mattis quam id urna. Vivamus dui. Donec nonummy lacinia lorem. Cras risus arcu, sodales ac, ultrices ac, mollis quis, justo. Sed a libero. Quisque risus erat, posuere at, tristique non, lacinia quis, eros.</p>
<!-- /wp:paragraph -->

<!-- wp:quote {"align":"left"} -->
<blockquote class="wp-block-quote has-text-align-left"><p>quote left</p></blockquote>
<!-- /wp:quote -->

<!-- wp:quote {"align":"right"} -->
<blockquote class="wp-block-quote has-text-align-right"><p>quote right</p></blockquote>
<!-- /wp:quote -->

<!-- wp:quote {"align":"center"} -->
<blockquote class="wp-block-quote has-text-align-center"><p>quote center</p></blockquote>
<!-- /wp:quote -->

<!-- wp:image {"align":"left","id":1866,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="alignleft size-large"><img src="http://localhost/current/wordpress/wp-content/uploads/spectacles.gif" alt="" class="wp-image-1866"/><figcaption>aligned left</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Cras volutpat, lacus quis semper pharetra, nisi enim dignissim est, et sollicitudin quam ipsum vel mi. Sed commodo urna ac urna. Nullam eu tortor. Curabitur sodales scelerisque magna. Donec ultricies tristique pede. Nullam libero. Nam sollicitudin felis vel metus. Nullam posuere molestie metus. Nullam molestie, nunc id suscipit rhoncus, felis mi vulputate lacus, a ultrices tortor dolor eget augue.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"align":"right","id":1866,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="alignright size-large"><img src="http://localhost/current/wordpress/wp-content/uploads/spectacles.gif" alt="" class="wp-image-1866"/><figcaption>align right</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> Aenean ultricies felis ut turpis. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Suspendisse placerat tellus ac nulla. Proin adipiscing sem ac risus. Maecenas nisi. Cras semper.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Praesent interdum mollis neque. In egestas nulla eget pede. Integer eu purus sed diam dictum scelerisque. Morbi cursus velit et felis. Maecenas faucibus aliquet erat. </p>
<!-- /wp:paragraph -->

<!-- wp:image {"align":"center","id":1866,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="http://localhost/current/wordpress/wp-content/uploads/spectacles.gif" alt="" class="wp-image-1866"/><figcaption>align center</figcaption></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>In aliquet rhoncus tellus. Integer auctor nibh a nunc fringilla tempus. Cras turpis urna, dignissim vel, suscipit pulvinar, rutrum quis, sem. Ut lobortis convallis dui. Sed nonummy orci a justo. Morbi nec diam eget eros eleifend tincidunt.</p>
<!-- /wp:paragraph -->

<!-- wp:pullquote {"align":"left"} -->
<figure class="wp-block-pullquote alignleft"><blockquote><p>pullquote</p><cite>align left</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:pullquote {"align":"right"} -->
<figure class="wp-block-pullquote alignright"><blockquote><p>pullquote</p><cite>align right</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:paragraph -->
<p>Curabitur non elit. Pellentesque iaculis, nisl non aliquet adipiscing, purus urna aliquet orci, sed sodales pede neque at massa. Pellentesque laoreet, enim eget varius mollis, sapien erat suscipit metus, sit amet iaculis nulla sapien id felis. Aliquam erat volutpat. Nam congue nulla a ligula. Morbi tempor hendrerit erat. Curabitur augue. Vestibulum nulla est, commodo et, fringilla quis, bibendum eget, ipsum. Suspendisse pulvinar iaculis ante. </p>
<!-- /wp:paragraph -->

<!-- wp:pullquote {"align":"wide"} -->
<figure class="wp-block-pullquote alignwide"><blockquote><p>pullquote</p><cite>align wide</cite></blockquote></figure>
<!-- /wp:pullquote -->

<!-- wp:button {"align":"left"} -->
<div class="wp-block-button alignleft"><a class="wp-block-button__link" href="#">button left</a></div>
<!-- /wp:button -->

<!-- wp:paragraph -->
<p>Mauris dignissim ante quis nisi. Aliquam ante mi, aliquam et, pellentesque ac, dapibus et, enim. In vulputate justo vel magna. Phasellus imperdiet justo. </p>
<!-- /wp:paragraph -->

<!-- wp:button {"align":"right"} -->
<div class="wp-block-button alignright"><a class="wp-block-button__link" href="#">button right</a></div>
<!-- /wp:button -->

<!-- wp:paragraph -->
<p>Proin odio orci, dapibus id, porta a, pellentesque id, erat. Aliquam erat volutpat. Mauris nonummy varius libero. Sed dolor ipsum, tempor non, aliquet et, pulvinar quis, dui. Pellentesque mauris diam, lobortis id, varius varius, facilisis at, nulla.</p>
<!-- /wp:paragraph -->

<!-- wp:button {"align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link" href="#">button center</a></div>
<!-- /wp:button -->

<!-- wp:media-text {"mediaId":1866,"mediaType":"image"} -->
<div class="wp-block-media-text alignwide"><figure class="wp-block-media-text__media"><img src="http://localhost/current/wordpress/wp-content/uploads/spectacles.gif" alt="" class="wp-image-1866"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">media, text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>media on left</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:media-text {"mediaPosition":"right","mediaId":1866,"mediaType":"image"} -->
<div class="wp-block-media-text alignwide has-media-on-the-right"><figure class="wp-block-media-text__media"><img src="http://localhost/current/wordpress/wp-content/uploads/spectacles.gif" alt="" class="wp-image-1866"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">media, text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>media on right</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->

<!-- wp:paragraph -->
<p>Cras pede. Nullam id velit sit amet turpis tincidunt sagittis. Nunc <strong>malesuada.</strong> Nunc consequat <em><strong>scelerisque odio</strong></em>. Donec eu leo. Nunc pellentesque felis sed odio. <em>Lorem</em> ipsum dolor sit amet, consectetuer adipiscing elit. Vivamus lobortis metus in lectus. Cras mollis quam eget <strong>sapien</strong>. Pellentesque non lorem sit amet sem lacinia euismod.</p>
<!-- /wp:paragraph -->
```

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #773 

<table>
<tr>
<td>Before:
<br><br>

#773 - before

</td>
<td>After:
<br><br>

#773 - after

</td>
</tr>
</table>

### CODE REVIEW

**Comment by joyously** [comment]
Your after image shows the wrong thing for the quote with text aligned right. The line (border or box-shadow?) is on the left instead of the right.
And I don't quite get what the Media/Text blocks are doing (you are saying these are correct?)

**Comment by nielslange** [comment]
> Your after image shows the wrong thing for the quote with text aligned right. The line (border or box-shadow?) is on the left instead of the right.

You are correct. The borders need to be adjusted. I'll update the PR accordingly.

> And I don't quite get what the Media/Text blocks are doing (you are saying these are correct?)

Nope, I never said that what the Media/Text blocks are doing is correct. I said that this issue is a core issue and should be addressed there instead of the theme. If you switch to Twenty Nineteen you'll see exactly the same, wrong behaviour for the Media/Text blocks. Therefore, I believe the root of the issue should be fixed, which would be in core rather in the theme.

**Comment by joyously** [comment]
Ah, I see that Media/Text is messed up even with my theme that doesn't style the blocks. (I thought I had seen it correct, before.)
Did you open an issue for Gutenberg to fix it? And is it just the image or the text alignment also?

**Comment by nielslange** [comment]
> Ah, I see that Media/Text is messed up even with my theme that doesn't style the blocks. (I thought I had seen it correct, before.)
> Did you open an issue for Gutenberg to fix it? And is it just the image or the text alignment also?

I just opened an issue on https://github.com/WordPress/gutenberg/issues/17922 and this issue only affects the alignments of the media but not the alignments of the text. Thus, a left-aligned text will remain left-aligned and a right-aligned text will remain right-aligned.

I also updated the PR, as promised in https://github.com/WordPress/twentytwenty/pull/844#issuecomment-541336978, and the border of the blockquotes shows on the correct side now. I've updated the screenshots accordingly.

**Pull request merged**
