### PR TITLE
#8 - Move page links outside content area 

### PR DESCRIPTION
**Pull request by c4rl0sbr4v0**
Would this be a solution for #8 ? I don't know if any CSS change is needed.

Thanks and let me know if need help with something!

### CODE REVIEW

**Comment by c4rl0sbr4v0** [comment]
Tested in Firefox 69.0, Safari Version 12.1.2 (14607.3.9), Chrome Version 76.0.3809.132 (Official Build) (64-bit)

Screenshot 2019-09-15 at 21 18 10
Screenshot 2019-09-15 at 21 14 39
Screenshot 2019-09-15 at 21 14 32
Screenshot 2019-09-15 at 21 12 28
Screenshot 2019-09-15 at 21 12 04

**Comment by joyously** [comment]
Why did you add a div around them?
Your screenshots don't even show any of the page links. It looks like you are using the them unit test data. You can find a page link on the Post format: Gallery post. Or edit any post or page (it would be good to test both) and add `<!--nextpage-->` to it to get a page link.

**Comment by c4rl0sbr4v0** [comment]
Sorry, I mistake pagination with link pages 😅 
I have no reason to add those divs, so I removed.
I tested on the same editors. Should we remove the left padding?
Screenshot 2019-09-16 at 00 05 56
Screenshot 2019-09-16 at 00 03 15
Screenshot 2019-09-16 at 00 03 04
Screenshot 2019-09-16 at 00 02 15

**Comment by joyously** [comment]
That is much better!

**Comment by carolinan** [comment]
I think the edit links need to be moved below it.

**Comment by joyously** [comment]
That would be a different PR. 
I think the Edit links are not that important since the visitor does not see them.

**Comment by carolinan** [comment]
The edit link was below the pagination before the changes were made.

**Comment by c4rl0sbr4v0** [comment]
Moved the edit link to be below the page links.

Screenshot 2019-09-17 at 12 19 34
Screenshot 2019-09-17 at 12 18 22

**Comment by c4rl0sbr4v0** [comment]
Sorry, I messed the pull request merging latest changes from master. Let me create a new one clean.

**Pull request closed without merging**
