### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by senadir**
this PR add support for RTL by adding rtlcss & running it.

It also adds the npm CLI command `npm run build:rtl` to generate a new rtl file.

It also adds the RTL file in function so it can be loaded when needed.

## How to test
* after pulling this PR, run `npm install` to install dependencies, it should be noted that you must have both [node & npm](https://nodejs.org/en/download/) (npm is bundled with node) installed in your machine, [this tutorial might help you](https://javascriptforwp.com/how-to-install-npm-and-node-on-a-mac/)
* run `npm run build:rtl` to generate the new RTL file
* either switch the site language to an RTL one (arabic, hebrew, urdu, persian...) or install this handy plugin [RTL tester](https://wordpress.org/plugins/rtl-tester/)
* verify that everything is well aligned.

### note
there is a big about an unflipped arrow in the post pagination section.

### CODE REVIEW

**Comment by senadir** [comment]
@ntwb Prettier fix to functions.php is now removed and this is ready for a review

**Comment by joyously** [comment]
I'm not sure what the status of having a build process is, but I find that it is so much easier to put the RTL rules in style.css. That way any change there is easy to make in the RTL style right next to it.

**Comment by ntwb** [comment]
TwentyNineteen used _build tooling_ to compile the RTLCSS, I think we should continue in that fashion and leave it up to the _machines_ to automate this for us 😏

https://github.com/WordPress/twentynineteen/blob/master/package.json#L19

**Comment by ntwb** [comment]
> there is a big about an unflipped arrow in the post pagination section.

Can you follow this up by creating an issue for this once this PR is merged please @senadir

**Comment by joyously** [comment]
I see the generated style sheet, but it doesn't seem to be loaded in RTL mode.

**Comment by pattonwebz** [comment]
@joyously you were too quick for me by about 40 seconds haha

**Pull request merged**
