### PR TITLE
Rename license.txt to LICENSE

### PR DESCRIPTION
**Pull request by nielslange**
Renamed license file name to reflect the used license within the summary of https://github.com/WordPress/twentytwenty:

Screenshot 2019-09-22 at 15 35 05

### CODE REVIEW

**Comment by jeffpaul** [comment]
@nielslange @ntwb is there a .org requirement for themes to have a license.txt file or are we ok to make this change?

**Comment by ntwb** [comment]
@jeffpaul Themes should have a license, and this change matches the 2019 format:
https://github.com/WordPress/twentynineteen/blob/master/LICENSE

**Comment by joyously** [comment]
It's not a required file, but it's recommended. The name doesn't matter.

**Comment by nielslange** [comment]
@jeffpaul & @joyously By renaming the file the license type is shown in Github. Currently it only says “License”.

**Pull request merged**
