### PR TITLE
Disable search button in mobile view

### PR DESCRIPTION
**Pull request by acosmin**
Fix for #210

### CODE REVIEW

**Comment by carolinan** [comment]
replace the : and the endif with braces

**Comment by acosmin** [comment]
@carolinan I thought of doing that :) but the entire file uses that style... should I really do it?

**Comment by acosmin** [comment]
The file needs an entire rewrite

**Comment by acosmin** [comment]
Done :)

**Comment by acosmin** [comment]
Wait, I made a little mistake

**Comment by carolinan** [comment]
I believe the next big change to this file will be if the menus are changed. So a full rewrite should probably be made then.

**Comment by acosmin** [comment]
Anyway, I think I got it right this time. It works...

**Comment by acosmin** [comment]
@carolinan I think this one can be merged...

**Comment by acosmin** [comment]
Redoing this...

**Pull request closed without merging**
