### PR TITLE
Replace FontAwesome with SVG icons

### LINKED ISSUE #674: Remove FontAwesome and replace it with an svg solution
Twenty Nineteen don't use any font icon, instead it has a class that take care of outputting the SVG code of the icons where they are used : https://github.com/WordPress/twentynineteen/blob/master/classes/class-twentynineteen-svg-icons.php

Doing the same will help to reduce the size of the theme ( https://github.com/WordPress/twentytwenty/issues/542 ), and help making the front-end a little faster, since the browser wouldn't have to download the font assets.

### PR DESCRIPTION
**Pull request by andersnoren**
Fixes #674 by replacing FontAwesome, which was previously used for the social menu, with an SVG solution based on the one used in Twenty Nineteen.

This PR:
- Removes the FontAwesome files, enqueues and stylesheets
- Adds Socicon SVGs as a separate array of icons in `classes/class-twentytwenty-svg-icons.php` and updates existing functions to support two different groups
- Adds a `walker_nav_menu_start_el` filter to the social menu that adds the appropriate SVG based on the menu item URL
- Replaces FontAwesome licensing information with Socicon information
- Fixes an IE11 footer social menu wrapping issue, and removes an unnecessary wrapping div around the footer social `nav` element

### CODE REVIEW

**Comment by ianbelanger79** [comment]
@andersnoren can you resolve the conflicts in `template-parts/footer-menus-widgets.php`? Then I will merge. Thanks

**Comment by andersnoren** [comment]
@ianbelanger79 Check!

**Comment by briceduclos** [comment]
Hello @andersnoren ! 
I was using the `twentytwenty_svg_icons` filter to change the Facebook svg (to use the official one)

The filter has been removed, can it be re-added? 

https://github.com/WordPress/twentytwenty/blob/ed551762647d2e5ad975198b02a709d79aabd188/classes/class-twentytwenty-svg-icons.php#L23-L24

**Comment by andersnoren** [comment]
@briceduclos Sorry about that – I should have included a replacement filter. I've added one per group of icons in #770.

**Comment by ianbelanger79** [comment]
Hi @briceduclos What is your WP username? Please let me know asap, thanks.

**Pull request merged**
