### PR TITLE
Range control for cover template opacity

### PR DESCRIPTION
**Pull request by LittleBigThing**
A range control to adjust the opacity of the cover template (step = 10 with min. 0 and max. 100)

fixing #276

### CODE REVIEW

**Comment by joyously** [comment]
Why use a step of 10?
And there is concern about using max of 100...

**Comment by LittleBigThing** [comment]
I agree to use steps of `5`. I just did a quick implementation based on your suggestion to make it testable. It might all still depend on decision about the opacity limits (#470)?

**Comment by ianbelanger79** [comment]
I updated #470 with the latest information on this issue. You can resume work on this PR, with one suggestion, could we show the actual number you are selecting when using the range slider? Thanks

**Comment by LittleBigThing** [comment]
Great, I will update the PR asap.

**Comment by joyously** [comment]
I don't think the number should be shown. That's the whole point of using a range control.

**Comment by acosmin** [comment]
@ianbelanger79 why was the blend mode option removed in this PR?

**Comment by LittleBigThing** [comment]
@acosmin see this reply https://github.com/WordPress/twentytwenty/issues/470#issuecomment-534591170

We should have done it in 2 separate PRs maybe, if that is what you meant. I thought it was related enough.

**Comment by acosmin** [comment]
@LittleBigThing thanks, I didn't know that.

**Comment by ianbelanger79** [comment]
@LittleBigThing sorry, I should've seen this before merging. We also plan to remove the `mix-blend-mode` because it is not supported in IE11 or Edge

**Comment by LittleBigThing** [comment]
Ok. So it’s just an overlay with opacity?
A separate PR will do it.

**Pull request merged**
