### PR TITLE
Using core's post navigation and pagination functions

### PR DESCRIPTION
**Pull request by anace**
This PR solves issue #300 (use core functionality for single navigation). Core's post navigation is accessibility ready and simpler to use. Besides, one of the Team Review Theme requirements is to use core functions when they exist.

In my PR, I kept the old code, both in `navigation.php` and in the stylesheet, so the original navigation and the new can be compared on the browser. There are indications on the two files around the code that has to be deleted in case the request is accepted.

WordPress username: acalfieri

### CODE REVIEW

**Comment by pattonwebz** [comment]
In the case of the single post navigation styles for both approaches look the same in my browser. Markup is a bit different.

Upper = original, Lower = addition in this PR.
Screenshot from 2019-09-18 02-18-13

Upper:
```
<nav class="pagination-single section-inner" aria-label="Post">

		
			<a class="previous-post" href="http://local.themereview/2009/05/edge-case-nested-and-mixed-lists">
				<span class="arrow">←</span>
				<span class="title"><span class="title-inner">Edge Case: Nested And Mixed Lists</span></span>
			</a>

			
			<a class="next-post" href="http://local.themereview/2009/07/edge-case-many-categories">
				<span class="arrow">→</span>
					<span class="title"><span class="title-inner">Edge Case: Many Categories</span></span>
			</a>
			
	</nav>
```
Lower:

```
    <nav class="navigation post-navigation" role="navigation">
		<h2 class="screen-reader-text">Post navigation</h2>
		<div class="nav-links"><div class="nav-previous"><a href="http://local.themereview/2009/05/edge-case-nested-and-mixed-lists" rel="prev"><span class="arrow" aria-hidden="true">←</span><span class="screen-reader-text">Previous post:</span><span class="post-title">Edge Case: Nested And Mixed Lists</span></a></div><div class="nav-next"><a href="http://local.themereview/2009/07/edge-case-many-categories" rel="next"><span class="arrow" aria-hidden="true">→</span><span class="screen-reader-text">Next post:</span><span class="post-title">Edge Case: Many Categories</span></a></div></div>
	</nav>
```

Posts with no titles are handled better with the `the_post_navigation()` 

Screenshot from 2019-09-18 02-15-16

**Comment by carolinan** [comment]
How does it handle the styling for when there is only one arrow? On the first and last page.

**Comment by carolinan** [comment]
The numbers are meant to be centered:

numbers

See https://github.com/WordPress/twentytwenty/issues/99

**Comment by carolinan** [comment]
Below 1000 pixels the spacing is not correct:

numbers2

**Comment by carolinan** [comment]
I am still super confused. Can these be split into two separate pull requests, one for each navigation,
and then remove the CSS that would no longer be used?

**Comment by carolinan** [comment]
@afercia Is using the screen reader text from the default markup acceptable here? Or does it need to be an aria label? https://github.com/WordPress/twentytwenty/issues/73

**Comment by afercia** [comment]
@carolinan good question and thanks for the ping! There's a core Trac ticket aimed to add the missing `aria-label` to the various post(s) / comments navigation. See:

The post(s) navigation landmark needs to be labelled
https://core.trac.wordpress.org/ticket/47123

Hopefully will be committed soon in core. Some testing would be nice 🙂

**Comment by carolinan** [comment]
Since the label hopefully will be included in 5.3, that's one less reason for using the custom markup.

**Comment by anace** [comment]
If you accept the change, I can continue working with the styles, so it looks like in the design.

**Comment by carolinan** [comment]
This PR cant be merged, it needs to be updated and any duplicate code and CSS must be removed.

**Comment by anace** [comment]
I'll close this PR and start from the beginning.

**Pull request closed without merging**
