### PR TITLE
Remove escape in translations.

### PR DESCRIPTION
**Pull request by juanfra**
Just like core, default themes don't escape translations when not necessary as those are trusted.

See these links for background.

https://core.trac.wordpress.org/ticket/30724
WordPress/twentynineteen#285 (comment)

*Fixes:* https://github.com/WordPress/twentytwenty/issues/176

WP Username: juanfra

### CODE REVIEW

**Comment by pattonwebz** [comment]
While core does not escape translations I am not so certain that is the correct thing due to the possibility of unexpected entities being present in languages used by the translator. I left a comment on that ticket linked stating such but lets hear what others think about it too.

**Comment by juanfra** [comment]
Thanks for the follow-up! There has been a discussion around this topic in a core ticket, but it was for the built-in themes.

Here's the discussion, where @ocean90 explains why these shouldn't be escaped: https://core.trac.wordpress.org/ticket/30724#comment:10

I've been searching a bit to see if there's a more recent discussion and it seems that for twentynineteen, the decision was the same: https://github.com/WordPress/twentynineteen/pull/523

**Comment by pattonwebz** [comment]
I have looked into this some more and previous themes do not escape this but they do translate it. I will pull down this PR and add in a comment to allow travis to pass with this PR.

**Comment by pattonwebz** [comment]
I rolled this PR into #441 and it got commit without me adding a close tag. I am closing this one here as the code is already merged but props should still be granted to `@juanfra` | WP Username: `juanfra`. #399

**Pull request closed without merging**
