### PR TITLE
Accent color hue reset on active callback

### PR DESCRIPTION
**Pull request by acosmin**
A prototype for the suggestion made in #583

The Accent color hue control will activate/deactivate based on a checkbox. Also, it will reset its value on deactivate.

### CODE REVIEW

**Comment by aristath** [comment]
I like it 👍

**Comment by nielslange** [comment]
@acosmin Functionality wise I love your prototype. However, from a usability point of view, wouldn't it be possible to have a simple reset button below the `Accent Color Hue` slider that sets the colour back to `#a73050`?

**Comment by acosmin** [comment]
@nielslange it is possible 😄 @aristath described it best in the issue mentioned above.

**Comment by aristath** [comment]
> However, from a usability point of view, wouldn't it be possible to have a simple reset button below the `Accent Color Hue slider` that sets the colour back to `#a73050`?

This is one of those weird issues where we wave to tread carefully...
Yes, UX-wise it would be better to just have a reset button.
But that would require 1 of 2 things:
1. Build a custom control to override the default WP Color control, and add the reset button there.
2. Inject it via JS

I don't know if adding a custom control would be recommended considering this is a core theme, and injecting via JS seems hacky and ugly (code-wise).

It's a thin line we have to walk.

The above implementation may not be the best choice for UX, but it's the most native choice and "the WP way". Unfortunately "_the WP way_" usually means doing things we're not happy with to get around core limitations...

**Comment by nielslange** [comment]
@aristath Thanks for your detailed explanation. 😀

**Comment by joyously** [comment]
Which way did Twenty Seventeen and Twenty Nineteen do it?

**Comment by nielslange** [comment]
That was a great question, @joyously! This is how Twenty Nineteen handled the same colour issue:

Screen Capture on 2019-09-28 at 21-58-51

@aristath and @acosmin As Twenty Nineteen has that functionality it shouldn't be too hard to implement it in the same way, right? This would also be great for folks switching from Twenty Nineteen to Twenty Twenty as they can reuse already learned knowledge.

**Comment by aristath** [comment]
Well... The fact that twentynineteen did it that way doesn't necessarily mean that it's better than a checkbox.
They are both viable options.

**Comment by acosmin** [comment]
I can do it either way, I would prefer this option, but ...

The project leads should decide if something like this is wanted.

**Comment by nielslange** [comment]
> Well... The fact that twentynineteen did it that way doesn't necessarily mean that it's better than a checkbox. They are both viable options.

I agree with you. To me personally, the Twenty Nineteen approach is less confusing. But let's see how @andersnoren thinks about this. 😀

**Comment by carolinan** [comment]
As per the meeting, we want to use the radio buttons.

**Comment by acosmin** [comment]
@carolinan as requested 😄

**Comment by acosmin** [comment]
@andersnoren done 👍

**Comment by acosmin** [comment]
@ianbelanger79 I think this one can be merged 😄

**Pull request merged**
