### PR TITLE
Fixed - #133 Search modal and admin bar overlap issue

### PR DESCRIPTION
**Pull request by sandeshjangam**
#133 Fixed The search modal and admin bar overlap issue. Added CSS for the fix.

WordPress username - sandesh055

### CODE REVIEW

**Comment by acosmin** [comment]
This doesn't take into consideration mobile versions, you'll also need to add some media queries :)

**Comment by carolinan** [comment]
When I test this, there is a gap between the admin bar and search, 

Desktop:
search-desktop

782:
search-narrow

And at 600 there is no gap and no overlap, but it breaks:

search-600

**Comment by sandeshjangam** [comment]
@carolinan Issue is fixed now. I also fixed issue below 600 size.
 Scroll lock was causing an issue for admin bar below 600px.
Here is a video of a test [https://cl.ly/832f956a7a4c](https://cl.ly/832f956a7a4c)

**Comment by ianbelanger79** [comment]
Issue seems to have been fixed, so I am closing this PR

**Pull request closed without merging**
