### PR TITLE
UPDATE #55: Add PHPDocs to template files

### LINKED ISSUE #55: Add PHPDocs to template files
- [x] https://github.com/WordPress/twentytwenty/blob/master/404.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/comments.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/content.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/footer.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/header.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/index.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/pagination.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/singular.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/template-cover.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/template-full-width.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/modal-menu.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/modal-search.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/page-header.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-comment-walker.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-svg-icons.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-theme-customizer.php

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #55 

I've also run all template files again the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards).

### CODE REVIEW

**Comment by nielslange** [comment]
@carolinan Sure, I'll refresh the footer.php immediately.

**Comment by nielslange** [comment]
@carolinan Done! 😀

**Comment by ntwb** [comment]
It would be nice to land #11 first and then have this code tested by phpcs and on Travis CI then review this PR

**Comment by carolinan** [comment]
I am not sure what the best option is here, maybe to refresh the PR with only the file headers?

**Comment by carolinan** [comment]
I have now added the file docs to the files that were still missing them (3 files).

**Comment by ntwb** [comment]
With _most files_ here now out-of-date, simplifying the PR might be the best option, just the file headers sounds like a good way to go.

Aside: Generally trying to avoid large PRs such as this on a _highly active_ repo allows for both the contributor, reviewer, and mergers the time required to perform those actions without the PR becoming out of date too quickly.

**Comment by carolinan** [comment]
There might be some difference between this PR and the current file headers, there are likely file headers that can be improved, but closing this for now.

**Pull request closed without merging**
